// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: collectorv1/collector.proto

package collectorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRepositoryInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepositoryInfoRequest) Reset() {
	*x = GetRepositoryInfoRequest{}
	mi := &file_collectorv1_collector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoryInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryInfoRequest) ProtoMessage() {}

func (x *GetRepositoryInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collectorv1_collector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryInfoRequest.ProtoReflect.Descriptor instead.
func (*GetRepositoryInfoRequest) Descriptor() ([]byte, []int) {
	return file_collectorv1_collector_proto_rawDescGZIP(), []int{0}
}

func (x *GetRepositoryInfoRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GetRepositoryInfoRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type GetRepositoryInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Stars         int32                  `protobuf:"varint,3,opt,name=stars,proto3" json:"stars,omitempty"`
	Forks         int32                  `protobuf:"varint,4,opt,name=forks,proto3" json:"forks,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepositoryInfoResponse) Reset() {
	*x = GetRepositoryInfoResponse{}
	mi := &file_collectorv1_collector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoryInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryInfoResponse) ProtoMessage() {}

func (x *GetRepositoryInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collectorv1_collector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryInfoResponse.ProtoReflect.Descriptor instead.
func (*GetRepositoryInfoResponse) Descriptor() ([]byte, []int) {
	return file_collectorv1_collector_proto_rawDescGZIP(), []int{1}
}

func (x *GetRepositoryInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetRepositoryInfoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetRepositoryInfoResponse) GetStars() int32 {
	if x != nil {
		return x.Stars
	}
	return 0
}

func (x *GetRepositoryInfoResponse) GetForks() int32 {
	if x != nil {
		return x.Forks
	}
	return 0
}

func (x *GetRepositoryInfoResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_collectorv1_collector_proto protoreflect.FileDescriptor

const file_collectorv1_collector_proto_rawDesc = "" +
	"\n" +
	"\x1bcollectorv1/collector.proto\x12\fcollector.v1\"D\n" +
	"\x18GetRepositoryInfoRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\"\x9c\x01\n" +
	"\x19GetRepositoryInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05stars\x18\x03 \x01(\x05R\x05stars\x12\x14\n" +
	"\x05forks\x18\x04 \x01(\x05R\x05forks\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt2x\n" +
	"\x10CollectorService\x12d\n" +
	"\x11GetRepositoryInfo\x12&.collector.v1.GetRepositoryInfoRequest\x1a'.collector.v1.GetRepositoryInfoResponseB7Z5golang-course/task2/api/proto/collectorv1;collectorv1b\x06proto3"

var (
	file_collectorv1_collector_proto_rawDescOnce sync.Once
	file_collectorv1_collector_proto_rawDescData []byte
)

func file_collectorv1_collector_proto_rawDescGZIP() []byte {
	file_collectorv1_collector_proto_rawDescOnce.Do(func() {
		file_collectorv1_collector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_collectorv1_collector_proto_rawDesc), len(file_collectorv1_collector_proto_rawDesc)))
	})
	return file_collectorv1_collector_proto_rawDescData
}

var file_collectorv1_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_collectorv1_collector_proto_goTypes = []any{
	(*GetRepositoryInfoRequest)(nil),  // 0: collector.v1.GetRepositoryInfoRequest
	(*GetRepositoryInfoResponse)(nil), // 1: collector.v1.GetRepositoryInfoResponse
}
var file_collectorv1_collector_proto_depIdxs = []int32{
	0, // 0: collector.v1.CollectorService.GetRepositoryInfo:input_type -> collector.v1.GetRepositoryInfoRequest
	1, // 1: collector.v1.CollectorService.GetRepositoryInfo:output_type -> collector.v1.GetRepositoryInfoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_collectorv1_collector_proto_init() }
func file_collectorv1_collector_proto_init() {
	if File_collectorv1_collector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_collectorv1_collector_proto_rawDesc), len(file_collectorv1_collector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_collectorv1_collector_proto_goTypes,
		DependencyIndexes: file_collectorv1_collector_proto_depIdxs,
		MessageInfos:      file_collectorv1_collector_proto_msgTypes,
	}.Build()
	File_collectorv1_collector_proto = out.File
	file_collectorv1_collector_proto_goTypes = nil
	file_collectorv1_collector_proto_depIdxs = nil
}
